### ISSUE TITLE
Database or disk is null

### ISSUE THREAD

**Issue by anallg** [UMC-Utrecht-RWE/ConcePTION-Level1b#1] opened 2022-07-18 12:12 UTC
Hi, we have the following problem executing Level 1b. I don´t understand the cause of the error. There are 700Gb free. 
It has failed after the execution of VISIT_OCCURRENCE and EVENTS. 

Attached you can find a screenshot with all the files of our CDM. We are running the script in a 128Gb RAM server. 

Please, let me know if you need aditional information. 

![image](https://user-images.githubusercontent.com/102151171/179508554-365c3ba1-da92-4c18-9309-1c16f6551b0e.png)

LOG:
> system.time(source(paste0(projectFolder,"/p_steps/GetCounts.R")))
|--------------------------------------------------|
|==================================================|
[1] "Check colnames file VISIT_OCCURRENCE_AR.csv Some columns are excluded from the analyses"
[1] "In table VISIT_OCCURRENCE_AR.csv colls are missing and are added as empty columns. Please check if all needed columns are in the table"
|--------------------------------------------------|
|==================================================|
[1] "Check colnames file VISIT_OCCURRENCE_AS.csv Some columns are excluded from the analyses"
[1] "In table VISIT_OCCURRENCE_AS.csv colls are missing and are added as empty columns. Please check if all needed columns are in the table"
|--------------------------------------------------|
|==================================================|
[1] "Check colnames file VISIT_OCCURRENCE_CL.csv Some columns are excluded from the analyses"
[1] "In table VISIT_OCCURRENCE_CL.csv colls are missing and are added as empty columns. Please check if all needed columns are in the table"
|--------------------------------------------------|
|==================================================|
[1] "Check colnames file VISIT_OCCURRENCE_MA.csv Some columns are excluded from the analyses"
[1] "In table VISIT_OCCURRENCE_MA.csv colls are missing and are added as empty columns. Please check if all needed columns are in the table"
|--------------------------------------------------|
|==================================================|
[1] "Check colnames file VISIT_OCCURRENCE_MU.csv Some columns are excluded from the analyses"
[1] "In table VISIT_OCCURRENCE_MU.csv colls are missing and are added as empty columns. Please check if all needed columns are in the table"
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
Error: database or disk is full
Timing stopped at: 7704 871.2 1.676e+04

**Comment by anallg** [comment] 2022-07-19 08:30
@t-andresvaz @relbersumcu @acidroyo-UMCU
I tag you because I´m not sure if github warns you somehow(email, etc....)

**Comment by relbersumcu** [comment] 2022-07-19 15:05
@anallg this this error also occured while running the matching script? And what is the total size of all the csv files in the CDM?

**Comment by anallg** [comment] 2022-07-19 16:53
@relbersumcu what is the "matching script" you are referring to? The total size of the files is 112Gb.

**Comment by relbersumcu** [comment] 2022-07-20 07:07
@anallg  Which DAP are you from? For pfizer interim 1 there was the analytical script in which there was a matching procedure. https://github.com/VAC4EU/C4591021_PfizerUMC

For 1 DAP that used linux there was also an error with disk space. 

However, I was not able to reproduce or explain they error since the maximum allowed size is much higher.
https://www.sqlite.org/limits.html#:~:text=The%20maximum%20size%20of%20a,281474%20gigabytes%20or%20256%2C000%20gibibytes).

So I have the following questions for now:
1. What is the system you are working with? Linux/windows/mac?
2. Are there several processes/scripts running at the same time?
3. After the failed run, what is the size of the file in \g_intermediate\database.db
4. Are you sure that the 700Gb free space you did mention is the space on the same drive as where the script is stored/ ran from?

**Comment by anallg** [comment] 2022-07-20 07:41
@relbersumcu 

We are from BIFAP- AEMPS(Spain). We don´t participate in Pfizer study. 

What is the system you are working with? Linux/windows/mac? **Windows**
Are there several processes/scripts running at the same time? **No. It´s only running this script**
After the failed run, what is the size of the file in \g_intermediate\database.db
![image](https://user-images.githubusercontent.com/102151171/179923054-b6aea5c3-2866-4cfa-9243-9072572f737e.png)

Are you sure that the 700Gb free space you did mention is the space on the same drive as where the script is stored/ ran from?
![image](https://user-images.githubusercontent.com/102151171/179923140-4c437a71-4137-4441-bc15-ccd5a5d839f3.png)

Please let me know if you need anything else.

**Comment by relbersumcu** [comment] 2022-07-20 09:16
@anallg 
So the database has a size of 100 GB, from which I would say that should be not the problem.
The next step would be then to know for sure in which line/code the error occurs. Therefore, we may need the script step by step.

Can you send me a screenshot of the global enviroment like the follwoing example:

![image](https://user-images.githubusercontent.com/71712013/179945628-8d13ff4e-3f06-4413-b8df-8cc5cc77d813.png)

**Comment by anallg** [comment] 2022-07-20 09:33
@relbersumcu 

![image](https://user-images.githubusercontent.com/102151171/179949301-a36b6293-ce1b-494f-869d-1bf8081df96a.png)

**Comment by anallg** [comment] 2022-07-20 11:08
@relbersumcu 
Same error: 
VALUES <- dbGetQuery(mydb,paste0("SELECT count(*) AS N,",paste0(colls, collapse = ",")," FROM ",j," GROUP BY ",paste0(colls, collapse = ",")))                  
Error: database or disk is full

**Comment by anallg** [comment] 2022-07-20 11:48
@relbersumcu 
Maybe is using C. Right now before executing this command I´ve look C disk full(in red) but now it´s ok again. Maybe is using C like cache, temp or something like that?

**Comment by anallg** [comment] 2022-07-20 11:53
@relbersumcu @t-andresvaz Yes, confirmed. It´s taking the space from C during the exection.

**Comment by relbersumcu** [comment] 2022-07-20 11:53
@anallg just the verify, the new code did give back a result without the error?

**Comment by anallg** [comment] 2022-07-20 11:57
@relbersumcu It´s still running but I think it´s going to fail. C is already in red, only 5Gb free.

**Comment by anallg** [comment] 2022-07-20 12:18
@relbersumcu It fails. There are only 50Gb free in C

**Comment by relbersumcu** [comment] 2022-07-20 12:29
@anallg as it is runing on medicines. Can you tell me the size of all the medicines csv files added?

I need to look for a solid solution in this issue.

**Comment by anallg** [comment] 2022-07-20 12:33
@relbersumcu 
There are 10 medicines files and the total size is 78,2Gb. OK. I´m going to remove the medicines and rerun the script. I´ll tell you.

**Comment by t-andresvaz** [comment] 2022-08-24 10:35
We are planing to start using other databases, so we can improve time and size of files. Closed as won't fix.

**Closed by t-andresvaz** 2022-08-24 10:35 UTC
